### ISSUE TITLE
Cleaners doesn't seem functional

### ISSUE THREAD

**Issue by skarekrow** [jdugan6240/kak-bundle#16] opened 2024-10-07 18:54 UTC
Hello! Testing this out with this definition:
```
bundle tabs.kak https://github.com/enricozb/tabs.kak %{
  # buffers as tabs
  map global goto n '<esc>: buffer-next<ret>'           -docstring 'next buffer'
  map global goto p '<esc>: buffer-previous<ret>'       -docstring 'previous buffer'
  map global user b ': enter-user-mode tabs<ret>'       -docstring 'tabs'
  map global user B ': enter-user-mode -lock tabs<ret>' -docstring 'tabs (lock)'

  set-option global tabs_modelinefmt '%val{cursor_line}:%val{cursor_char_column} {{mode_info}} '
  set-option global tabs_options --minified
}

bundle-install-hook tabs.kak %{
  # Any shell code that needs to be run goes here...
  cargo install --locked --force --path .
}

bundle-cleaner tabs.kak %{
  rm ~/.cargo/bin/kak-tabs
}
```

Anytime I run `:bundle-clean tabs.kak` I get back `/bin/sh: line 24: kak_opt_bundle_cleaners: unbound variable`. 

This is an example, but it happens with any plugin. I'm running v2024.05.18 of Kakoune, with the latest release of `kak-bundle`

EDIT: I should also note that I can manually verify that binary still exists at `~/.cargo/bin/kak-tabs`, so the removal is not happening.

Also as a side note, thank you for this plugin! It's wonderful and has made my kakrc so clean!

**Comment by jdugan6240** [comment] 2024-10-08 03:17
Interesting. I haven't had trouble with cleaners personally, but I don't doubt your report.

Thanks for the reproducer. This is a busy week for me unfortunately, so it may be some time before I can investigate this.

In the meantime, I'd suggest the following workaround.

In your kakrc, write the following:

```kak
define-command clean-tabs-kak %{
    nop %sh{
        rm -rf "$kak_opt_bundle_path/tabs.kak" "$kak_opt_bundle_path/tabs.kak-load.kak"
        rm ~/.cargo/bin/kak-tabs # cleaner
    }
}
```

That lets you use `clean-tabs-kak` to do basically what `bundle-clean tabs.kak` *should* do. For other plugins, replace `tabs.kak` with whatever plugin name fits.

**Comment by jdugan6240** [comment] 2024-10-08 18:31
Github's fine. I purposely allow issues and pull requests on both, in case someone prefers one platform over another, but I mostly use Codeberg for development, with Github as a mirror.

**Comment by skarekrow** [comment] 2024-10-08 18:39
Yeah experiments there didn't yield anything meaningful. This is bizarre. Even if I hardcode the path the `rm` doesn't fire as you'd expect.

**Comment by jdugan6240** [comment] 2024-10-08 19:13
Given the error you were getting, the only explanations that make sense are that either bundle_cleaners isn't getting initialized, or the bundle-clean command somehow doesn't have `kak_opt_bundle_cleaners` in scope.

Would you mind posting the contents of your `debug` buffer on startup?

**Comment by skarekrow** [comment] 2024-10-08 20:46
Sure!

Before:
```
*** This is the debug buffer, where debug info will be written ***
error running hook User(bundle-loaded=kak-tree-sitter)/bundle-loaded: 2:3: 'eval': no selections in context
shell stderr: <<<
rm: : No such file or directory
>>>
```

After:
```
*** This is the debug buffer, where debug info will be written ***
error running hook User(bundle-loaded=kak-tree-sitter)/bundle-loaded: 2:3: 'eval': no selections in context
shell stderr: <<<
rm: : No such file or directory
>>>
shell stderr: <<<
/bin/dash: 23: kak_opt_bundle_cleaners: parameter not set
echo -debug >>>
```

Not sure where these redirects are coming from, they're not in my kakrc. Perhaps they're from `kak-tree-sitter` as when I run this in an actual code repository I don't see this. I instead see something like this:
```
*** This is the debug buffer, where debug info will be written ***
error running hook User(bundle-loaded=kak-tree-sitter)/bundle-loaded: 2:3: 'eval': no selections in context
error running hook WinSetOption(filetype=go)/: 7:5: 'lsp-inline-diagnostics-enable': 2:5: 'add-highlighter': duplicate id: 'lsp_inline_diagnostics'
LSP: INFO kak-lsp server starting. To increase log verbosity, run 'set g lsp_debug true'
LSP: INFO Starting Language server gopls as `gopls`
LSP: log from gopls: 2024/10/08 15:43:54 Created View (#1)
	directory=/Users/bschneider/git/repo
	view_type="GoMod"
	root_dir="file:///Users/bschneider/git/repo"
	go_version="go version go1.22.6 darwin/arm64"
	build_flags=[]
	env={GOOS:darwin GOARCH:arm64 GOCACHE:/Users/bschneider/Library/Caches/go-build GOMODCACHE:/Users/bschneider/.go/pkg/mod GOPATH:/Users/bschneider/.go GOPRIVATE: GOFLAGS: GO111MODULE: GOTOOLCHAIN:auto GoVersion:22 GoVersionOutput:go version go1.22.6 darwin/arm64
 ExplicitGOWORK: EffectiveGOPACKAGESDRIVER:}
	env_overlay=[]
LSP: log from gopls: 2024/10/08 15:43:54 go/packages.Load #1
	view_id="1"
	snapshot=0
	directory=/Users/bschneider/git/repo
	query=[/Users/bschneider/git/repo/... builtin]
	packages=44
	duration=424.558666ms
Error: nothing left to undo
LSP: log from gopls: 2024/10/08 15:44:24 background imports cache refresh starting
LSP: log from gopls: 2024/10/08 15:44:25 background refresh finished after 941.075458ms
```

**Comment by jdugan6240** [comment] 2024-10-08 22:08
Ok, so this suggests that somehow, `bundle-clean` doesn't properly see the cleaners. That's... strange. I'll look into it when I get the chance.

**Comment by jdugan6240** [comment] 2024-10-14 20:34
Apologies for the delay - I was attending my brother's wedding.

I found the problem - basically, since `$kak_opt_bundle_cleaners` was never mentioned in the `%sh{}` block `bundle-clean` runs, Kakoune doesn't export it and thus, the error you were seeing.

I'll fix it when I get home from work.

**Comment by skarekrow** [comment] 2024-10-14 21:28
I was looking into it a bit, but I wasn't sure how this was all wired up. Every attempt ended up cleaning *every* plugin when I would export it, ends up either nuking every plugin (running each cleaner) or a no-op :D I'm not super familiar with how this is all inherited in Kakoune's environment yet to figure out exactly where to add this.

Appreciate the quick turnaround! Hope the wedding was great too!

**Comment by jdugan6240** [comment] 2024-10-14 23:28
For an idea of how this works, check out the bundle-clean command definition here: https://github.com/jdugan6240/kak-bundle/blob/master/rc/kak-bundle.kak#L288

You'll notice that there are several commented out variables. The reason we need to do this is that Kakoune exports any kak_* variables that are present in a `%sh{}` block, and any shell code sourced from that block is not searched, as doing so is not practical to implement. As a result, any variables we use in sourced functions, we need to reference here, and I simply forgot to do so for `kak_opt_bundle_cleaners`.

More information on the above can be seen here: https://github.com/mawww/kakoune/blob/master/doc/pages/expansions.asciidoc#shell-expansions

Does that make sense?

**Comment by skarekrow** [comment] 2024-10-14 23:35
Oh! I was wondering why they were all commented out, so I made a PR [here](https://github.com/jdugan6240/kak-bundle/pull/17), is that the correct way to add it?

**Comment by jdugan6240** [comment] 2024-10-15 00:20
Should be closed by the linked PR

**Closed by jdugan6240** 2024-10-15 00:20 UTC
